'use client'
import { NavBack } from "@/app/globalComponents/buttonFunctions";
import { 
  Spacer,
  Text,
} from "@chakra-ui/react";





const Page = () => {
  

  document.title = "Terms Of Service"
  

  return (  
    <div
      className="w-full bg-background flex flex-col justify-center p-2"
      itemType="https://schema.org/termsOfService"
      itemScope
    >
      <div className="w-full flex flex-row justify-around">
        <div className="flex flex-col justify-center p-4">
          <NavBack home />
        </div>

        <Spacer />
        <Text
          fontSize={"xxx-large"}
          fontFamily={"sans-serif"}
          fontWeight={600}
        >
          Voidback.
        </Text>
        <Spacer />
      </div>



      <div className="w-[80%] max-w-[600px] place-self-center flex flex-col justify-center place-items-center overflow-y-scroll">

          <div className="my-10 flex flex-col gap-2">
            <h1 className="font-bold">Voidback Terms of Service</h1>

            <p>By accessing or using any of Voidback's services, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, please do not use our services.</p>
          </div>


          <div className="my-10 flex flex-col gap-2">
            <h2 className="font-bold py-2">Use of Services</h2>
            <p className="font-bold">You may use our services for lawful purposes only. You may not use our services to:</p>
            <ul className="px-10 list-disc">
              <li>Violate any laws or regulations.</li>
              <li>Harm or threaten others.</li>
              <li>Engage in spam or other unsolicited communications.</li>
              <li>Attempt to gain unauthorized access to our systems or networks.</li>
            </ul>
          </div>


          <div className="my-10 flex flex-col gap-2">
            <h2 className="font-bold">Intellectual Property</h2>
             <p>Voidback owns all intellectual property rights, including copyrights, trademarks, and patents, in and to the Voidback services and their content. This includes, but is not limited to, posts, research, and any other content submitted to or generated by the platform.</p>
                <p>By submitting content to Voidback, you grant Voidback a worldwide, royalty-free, perpetual, irrevocable, non-exclusive license to use, reproduce, modify, adapt, publish, translate, create derivative works from,   
             distribute, and display such content in any media   
             or format, whether now known or hereafter devised.</p>
          </div>

          <div className="my-10 flex flex-col gap-2">
            <h2 className="font-bold">Disclaimer of Warranties</h2>
            <p>Voidback provides its services "as is" without any warranties, express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular   
         purpose, or non-infringement.</p>
          </div>


          <div className="my-10 flex flex-col gap-2">
            <h2 className="font-bold">Limitation of Liability</h2>
            <p>In no event shall   
         Voidback be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from   
         your access to or use of or inability to access or use the services.</p>   
          </div>


          <div className="my-10 flex flex-col gap-2">
            <h2 className="font-bold">Changes to Terms of Service</h2>
            <p>Voidback reserves the right to modify or replace these Terms of Service at any time. Your continued use of the Service after any such changes constitutes your acceptance   
         of the new Terms of Service.</p>
          </div>


        
          <div className="my-10 flex flex-col gap-2">
           <h2 className="font-bold">Language</h2>
            <p>Voidback currently operates in English. We reserve the right to expand our language support in the future.</p>
          </div>

          <div className="my-10 flex flex-col gap-2">
            <h2 className="font-bold">Termination</h2>
            <p>Voidback may terminate or suspend your access to the services immediately, without notice or liability, for any reason, including but not limited to violation of these Terms of Service.</p>
          </div>


          <div className="my-10 flex flex-col gap-2">
            <h2 className="font-bold">Governing Law</h2>
            <p>These Terms of Service shall be governed by and construed in accordance with the laws of   
       the State of Delaware, USA.</p>
          </div>


          </div>
      </div>

  )
}

export default Page;
